version: '2.1'

networks:
  default:
    external:
      name: app-network

volumes:
  postgresql_data:
    driver: local

services:
  postgresql:
    image: 'bitnami/postgresql:13.2.0'
    restart: unless-stopped
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - '5432:5432'